stages:
  - verify
verify:
  stage: verify
  image: maven:3.6.3-openjdk-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    - key: "${CI_JOB_NAME}"
      paths:
        - .sonar/cache
    - key: dependencies
      paths:
        - $CI_PROJECT_DIR/.m2/repository
    - key: dependency-check
      paths:
        - $CI_PROJECT_DIR/.dependency-check/data/
  script:
    - mvn verify -s $CI_MAVEN_SETTING_XML -U -DdataDirectory=$CI_PROJECT_DIR/.dependency-check/data
      sonar:sonar -Dsonar.projectKey=java_education_autkin_AZdT-_szMIS-HUvHjH7L
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop")'